apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-sdbd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-sdbd
    app.kubernetes.io/part-of: ci10t-777-0023-app
  name: devfile-sample-sdbd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-sdbd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-sdbd
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0023-tenant/ci10t-777-0023-app/devfile-sample-sdbd@sha256:06490e83c9e9ebaf50916667b6daf11147564394bbb3289da8a41962acd2060f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
