apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sdbd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0023-tenant/ci10t-777-0023-app/devfile-sample-sdbd@sha256:06490e83c9e9ebaf50916667b6daf11147564394bbb3289da8a41962acd2060f
        name: my-nodejs
        resources: {}
status: {}
